/*
 * TELA INICIAL

 */
package Telas;

import Controle.ImovelControle;
import Controle.LocacaoControle;
import Modelo.Imovel;
import Modelo.Locacao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;

public final class TelaInicial extends Cabecalho {
    
    private int id;
    
    public TelaInicial() {
        initComponents();       
        PreencheTableDisponiveis();
        PreencheTableLocado();
    }
    
    private Controle.ImovelControle imovel;
    
    /*
    *   METODO PARA PREENCHER A JTABLE COM OS IMÓVEIS DISPONÍVEIS
    *   Esse método é chamado pelo construtor da TelaInicial 
    *   Utiliza o Array List que retorna do método Imovelpara popular a JTableDisponivel
    */
    public void PreencheTableDisponiveis(){
        DefaultTableModel modelo = (DefaultTableModel) jTableDisponivel.getModel();
        
        modelo.setNumRows(0);//limpa as linhas para nao aparecer duplicado
        
        ImovelControle imvDao = new ImovelControle();
        
        imvDao.listaImovelDisponivel().stream().forEach((i) -> {
            modelo.addRow(new Object[]{
                 i.getId(),
                 i.getRua(),
                 i.getNumero(),
                 i.getBairro(),
                 i.getCidade(),
                 i.getEstado(),
                 i.getCEP(),
                 i.getTipo(),
                 i.getQtdQuarto(),
                 i.getTamanho(),
                 i.getValor(),
                 i.getObs()
            });
        });
    }
    
     /*
    *   METODO PARA PREENCHER A JTABLE COM OS IMÓVEIS LOCADOS
    *   Esse método é chamado pelo construtor da TelaInicial 
    *   Utiliza o Array List que retorna do método Imovelpara popular a JTableLocado
    */
    public void PreencheTableLocado(){
        DefaultTableModel modelo = (DefaultTableModel) jTableLocado.getModel();
        
        modelo.setNumRows(0);//limpa as linhas para nao aparecer duplicado
        
        LocacaoControle locaControle = new LocacaoControle();
        
        locaControle.listaImovelLocado().stream().forEach((i) -> {
            modelo.addRow(new Object[]{
                 i.getIdLocacao(),
                 i.getImovel().getTipo(),
                 i.getImovel().getCidade(),
                 i.getImovel().getEstado(),
                 i.getImovel().getCEP(),
                 i.getImovel().getRua(),
                 i.getImovel().getNumero(),
                 i.getImovel().getTamanho(),
                 i.getDataFinal(),
                 i.getImovel().getObs(),
                 i.getCliente().getNome(),
                 i.getValorLocacao()
            });
        });
    }
    /*
    *   METODO PARA PREENCHER A JTABLE COM OS IMÓVEIS LOCADOS
    *   Esse método é chamado pelo construtor da TelaInicial 
    *   Utiliza o Array List que retorna do método Imovelpara popular a JTableLocado
    */
   /* public void PreencheTableLocado(){
        DefaultTableModel modelo = (DefaultTableModel) jTableLocado.getModel();
        
        modelo.setNumRows(0);//limpa as linhas para nao aparecer duplicado
        
        ImovelControle imvDao = new ImovelControle();
        
        imvDao.listaImovelLocado().stream().forEach((i) -> {
            modelo.addRow(new Object[]{
                 i.getId(),
                 i.getRua(),
                 i.getNumero(),
                 i.getBairro(),
                 i.getCidade(),
                 i.getCEP(),
                 i.getTipo(),
                 i.getQtdQuarto(),
                 i.getTamanho(),
                 i.getValor(),
                 i.getObs()
            });
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPaneInicial = new javax.swing.JTabbedPane();
        jPanelDisponivel = new javax.swing.JPanel();
        jPanelRodapeDisponiveis = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonInserir = new javax.swing.JToggleButton();
        jButtonAlterar = new javax.swing.JToggleButton();
        jButtonExcluir = new javax.swing.JToggleButton();
        jButtonInformarLocacao = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonExcluir2 = new javax.swing.JToggleButton();
        jButtonExcluir1 = new javax.swing.JToggleButton();
        jButtonInformarLocacao1 = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableDisponivel = new javax.swing.JTable();
        jPanelLocado = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableLocado = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButtonEncerrarLocacao = new javax.swing.JToggleButton();
        jButtonDesfazerEncerrar = new javax.swing.JToggleButton();
        jButtonAlterarLocacao = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Aluguel de Imoveis");

        jTabbedPaneInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPaneInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Locação:"));

        jButtonInserir.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonInserir.setText("Novo");
        jButtonInserir.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jButtonInserirAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonAlterar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonAlterar.setText("Alterar");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonInformarLocacao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonInformarLocacao.setText("Informar");
        jButtonInformarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformarLocacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterar)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir)
                .addGap(0, 15, Short.MAX_VALUE))
            .addComponent(jButtonInformarLocacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonInformarLocacao)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários"));

        jButtonExcluir2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonExcluir2.setText("Cadastrar");
        jButtonExcluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluir2ActionPerformed(evt);
            }
        });

        jButtonExcluir1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonExcluir1.setText("Listar");
        jButtonExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonExcluir2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
            .addComponent(jButtonExcluir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonExcluir2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExcluir1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonInformarLocacao1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonInformarLocacao1.setText("Sair");
        jButtonInformarLocacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInformarLocacao1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRodapeDisponiveisLayout = new javax.swing.GroupLayout(jPanelRodapeDisponiveis);
        jPanelRodapeDisponiveis.setLayout(jPanelRodapeDisponiveisLayout);
        jPanelRodapeDisponiveisLayout.setHorizontalGroup(
            jPanelRodapeDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRodapeDisponiveisLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jButtonInformarLocacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelRodapeDisponiveisLayout.setVerticalGroup(
            jPanelRodapeDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRodapeDisponiveisLayout.createSequentialGroup()
                .addGroup(jPanelRodapeDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRodapeDisponiveisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelRodapeDisponiveisLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonInformarLocacao1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableDisponivel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Rua", "N°", "Bairro", "Cidade", "Estado", "CEP", "Tipo", "Quartos", "m²", "Valor", "Observação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableDisponivel);
        if (jTableDisponivel.getColumnModel().getColumnCount() > 0) {
            jTableDisponivel.getColumnModel().getColumn(0).setMinWidth(22);
            jTableDisponivel.getColumnModel().getColumn(0).setMaxWidth(35);
            jTableDisponivel.getColumnModel().getColumn(2).setMinWidth(30);
            jTableDisponivel.getColumnModel().getColumn(2).setMaxWidth(45);
            jTableDisponivel.getColumnModel().getColumn(6).setPreferredWidth(28);
            jTableDisponivel.getColumnModel().getColumn(7).setMinWidth(45);
            jTableDisponivel.getColumnModel().getColumn(7).setMaxWidth(60);
            jTableDisponivel.getColumnModel().getColumn(8).setMinWidth(40);
            jTableDisponivel.getColumnModel().getColumn(8).setMaxWidth(60);
            jTableDisponivel.getColumnModel().getColumn(9).setMinWidth(40);
            jTableDisponivel.getColumnModel().getColumn(9).setMaxWidth(60);
            jTableDisponivel.getColumnModel().getColumn(10).setMinWidth(45);
            jTableDisponivel.getColumnModel().getColumn(10).setMaxWidth(55);
        }

        javax.swing.GroupLayout jPanelDisponivelLayout = new javax.swing.GroupLayout(jPanelDisponivel);
        jPanelDisponivel.setLayout(jPanelDisponivelLayout);
        jPanelDisponivelLayout.setHorizontalGroup(
            jPanelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelRodapeDisponiveis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane4)
        );
        jPanelDisponivelLayout.setVerticalGroup(
            jPanelDisponivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDisponivelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRodapeDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPaneInicial.addTab("Imóveis Disponíveis", jPanelDisponivel);

        jTableLocado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Tipo", "Cidade", "CEP", "Rua", "Num", "Tamanho", "Fim do Contrato", "Observação", "Locatario", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableLocado);
        if (jTableLocado.getColumnModel().getColumnCount() > 0) {
            jTableLocado.getColumnModel().getColumn(0).setMinWidth(20);
            jTableLocado.getColumnModel().getColumn(0).setMaxWidth(35);
            jTableLocado.getColumnModel().getColumn(1).setMinWidth(35);
            jTableLocado.getColumnModel().getColumn(1).setMaxWidth(65);
            jTableLocado.getColumnModel().getColumn(2).setPreferredWidth(11);
            jTableLocado.getColumnModel().getColumn(3).setMinWidth(55);
            jTableLocado.getColumnModel().getColumn(3).setMaxWidth(80);
            jTableLocado.getColumnModel().getColumn(5).setMinWidth(25);
            jTableLocado.getColumnModel().getColumn(5).setMaxWidth(45);
            jTableLocado.getColumnModel().getColumn(6).setMinWidth(30);
            jTableLocado.getColumnModel().getColumn(6).setMaxWidth(65);
            jTableLocado.getColumnModel().getColumn(7).setMinWidth(90);
            jTableLocado.getColumnModel().getColumn(7).setMaxWidth(120);
            jTableLocado.getColumnModel().getColumn(8).setPreferredWidth(18);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Locação"));

        jButtonEncerrarLocacao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonEncerrarLocacao.setText("Encerrar");
        jButtonEncerrarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncerrarLocacaoActionPerformed(evt);
            }
        });

        jButtonDesfazerEncerrar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonDesfazerEncerrar.setText("Desfazer");
        jButtonDesfazerEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesfazerEncerrarActionPerformed(evt);
            }
        });

        jButtonAlterarLocacao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonAlterarLocacao.setText("Alterar");
        jButtonAlterarLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarLocacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonEncerrarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDesfazerEncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterarLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonEncerrarLocacao)
                .addComponent(jButtonDesfazerEncerrar)
                .addComponent(jButtonAlterarLocacao))
        );

        javax.swing.GroupLayout jPanelLocadoLayout = new javax.swing.GroupLayout(jPanelLocado);
        jPanelLocado.setLayout(jPanelLocadoLayout);
        jPanelLocadoLayout.setHorizontalGroup(
            jPanelLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLocadoLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLocadoLayout.setVerticalGroup(
            jPanelLocadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLocadoLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPaneInicial.addTab("Imóveis Locados", jPanelLocado);

        getContentPane().add(jTabbedPaneInicial, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarLocacaoActionPerformed
        //retorna o codigo da locaçao da Tabela locados
        if (jTableLocado.getSelectedRow() != -1) {
            setId((int) jTableLocado.getValueAt(jTableLocado.getSelectedRow(), 0));
        }
            LocacaoControle locacaoControle = new LocacaoControle();
            Locacao locacao = new Locacao();
            locacao = locacaoControle.retornaLocacao(id);
            
            TelaCadLocacao telaCadLocacao = new TelaCadLocacao(locacao);
            
            dispose();
            telaCadLocacao.setLocationRelativeTo(null);
            telaCadLocacao.setVisible(true);
    }//GEN-LAST:event_jButtonAlterarLocacaoActionPerformed
    
    /*
    *   BOTÃO PARA INFORMAR LOCAÇÃO DO IMÓVEL SELECIONADO
    *   Esse botão abre a TelaCadImovel, enviando o Objeto Imovel para preencher os campos da TelaCadLocação com os dados do imóvel selecionado
    */
    private void jButtonInformarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformarLocacaoActionPerformed
        Imovel imv = new Imovel();
        if (jTableDisponivel.getSelectedRow() != -1) {
             imv.setId((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 0));
            imv.setRua(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 1).toString());
            imv.setNumero((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 2));
            imv.setBairro(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 3).toString());
            imv.setCidade(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 4).toString());
            imv.setEstado(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 5).toString());
            imv.setCEP(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 6).toString());
            imv.setTipo(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 7).toString());
            imv.setQtdQuarto((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 8));
            imv.setTamanho((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 9));
            imv.setValor((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 10));
            imv.setObs(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 11).toString());
            
            TelaCadLocacao loc = new TelaCadLocacao(imv);
            loc.setLocationRelativeTo(null);
            dispose();
            loc.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um imóvel para informar locação!");
        }
    }//GEN-LAST:event_jButtonInformarLocacaoActionPerformed

    /*
    *   BOTÃO INSERIR NOVO IMÓVEL
    *   Esse botão abre a TelaCadImovel com os campos em branco
    */
    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        TelaCadImovel TCadImovel = new TelaCadImovel();
        TCadImovel.setLocationRelativeTo(null);
        TCadImovel.setVisible(true);
        PreencheTableDisponiveis();
        dispose();
    }//GEN-LAST:event_jButtonInserirActionPerformed
private boolean vr;
    
    /*
    *   BOTÃO PARA ALTERAR IMÓVEL SELECIONADO
    *   Esse botão abre a TelaCadImovel preenchendo os campos com os dados do imóvel selecionado para alteração
    */
    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        Imovel imv = new Imovel();
        if (jTableDisponivel.getSelectedRow() != -1) {
            imv.setId((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 0));
            imv.setRua(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 1).toString());
            imv.setNumero((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 2));
            imv.setBairro(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 3).toString());
            imv.setCidade(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 4).toString());
            imv.setEstado(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 5).toString());
            imv.setCEP(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 6).toString());
            imv.setTipo(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 7).toString());
            imv.setQtdQuarto((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 8));
            imv.setTamanho((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 9));
            imv.setValor((double) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 10));
            imv.setObs(jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 11).toString());
            
            TelaCadImovel TCadImovelAlterar = new TelaCadImovel(imv);
            
            TCadImovelAlterar.setLocationRelativeTo(null);
            TCadImovelAlterar.setVisible(true);
            dispose();

        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /*
    *   BOTÃO PARA EXCLUIR UM IMÓVEL DISPONÍVEL
    *   Esse botão chama o método deleteImovel da classa imovelDAO e envia o id do imóvel selecionado pelo usuário
    */
    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jTableDisponivel.getSelectedRow() != -1) {

            int opcao = JOptionPane.showConfirmDialog(null, "Realmente deseja encerrar a locacao?", "Aviso", JOptionPane.YES_NO_OPTION);

            if (opcao == 0) {
                ImovelControle dao = new ImovelControle();

                setId((int) jTableDisponivel.getValueAt(jTableDisponivel.getSelectedRow(), 0));

                dao.deleteImovel(id);
                PreencheTableDisponiveis();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonInserirAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jButtonInserirAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonInserirAncestorAdded

    private void jButtonEncerrarLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncerrarLocacaoActionPerformed
        setId(0);
        if (jTableLocado.getSelectedRow() != -1) {
            
            int opcao = JOptionPane.showConfirmDialog(null, "Realmente deseja encerrar a locacao?", "Aviso", JOptionPane.YES_NO_OPTION);

            if (opcao == 0) {
                LocacaoControle locacaoControle = new LocacaoControle();

                setId((int) jTableLocado.getValueAt(jTableLocado.getSelectedRow(), 0));
            
                locacaoControle.encerraLocacao(id);
                PreencheTableLocado();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma locacao para encerrar");
        }
        
    }//GEN-LAST:event_jButtonEncerrarLocacaoActionPerformed

    private void jButtonDesfazerEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesfazerEncerrarActionPerformed
        LocacaoControle locacaoControle = new LocacaoControle();
         locacaoControle.desfazEncerraLocacao(id);
         PreencheTableLocado();

    }//GEN-LAST:event_jButtonDesfazerEncerrarActionPerformed

    private void jButtonExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluir1ActionPerformed
        TelaUsuario uzer = new TelaUsuario();
        dispose();
        uzer.setLocationRelativeTo(null);
        uzer.setVisible(true);
    }//GEN-LAST:event_jButtonExcluir1ActionPerformed

    private void jButtonExcluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluir2ActionPerformed
        TelaCadastroUsuario tc = new TelaCadastroUsuario();
        dispose();
        tc.setLocationRelativeTo(null);
        tc.setVisible(true);
    }//GEN-LAST:event_jButtonExcluir2ActionPerformed

    private void jButtonInformarLocacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInformarLocacao1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonInformarLocacao1ActionPerformed

    public int getId() {
        return id;
    }
    public void setId(int id) {
        this.id = id;
    }

    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jButtonAlterar;
    private javax.swing.JToggleButton jButtonAlterarLocacao;
    private javax.swing.JToggleButton jButtonDesfazerEncerrar;
    private javax.swing.JToggleButton jButtonEncerrarLocacao;
    private javax.swing.JToggleButton jButtonExcluir;
    private javax.swing.JToggleButton jButtonExcluir1;
    private javax.swing.JToggleButton jButtonExcluir2;
    private javax.swing.JToggleButton jButtonInformarLocacao;
    private javax.swing.JToggleButton jButtonInformarLocacao1;
    private javax.swing.JToggleButton jButtonInserir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDisponivel;
    private javax.swing.JPanel jPanelLocado;
    private javax.swing.JPanel jPanelRodapeDisponiveis;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPaneInicial;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableDisponivel;
    private javax.swing.JTable jTableLocado;
    // End of variables declaration//GEN-END:variables
}
