/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Controle.ImovelControle;
import Controle.Validacao;
import Modelo.Imovel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.Visibility;
import javax.swing.JOptionPane;

/**
 *
 * @author klebe
 */
public class TelaCadImovel extends javax.swing.JFrame {

    private int id;
    private boolean vrUpDel;//Utiliza no if do botao Salvar. true: novo imóvel, e false: alterar imóvel
    
    
    /*
    * CONSTRUTOR UTILIZADO PARA O BOTÃO NOVO IMOVEL
    * Esse construtor inicializa a TelaCadImovel com os campos em branco,
    * e a variável vrUpDel como true significa que o botão salva é para inserir novo imóvel
    */
    public TelaCadImovel() {
        initComponents();
        vrUpDel = true;
    }
    /*
    * CONSTRUTOR UTILIZADO PARA O BOTÃO ALTERAR IMOVEL
    * Esse construtor inicializa a TelaCadImovel com os campos preenchidos com os dados do imovel selecionado na TelaInicial,
    * e a variável vrUpDel como false significa que o botão salva é para alterar o imóvel
    */
    public TelaCadImovel(Imovel imv) {//construtor utilizado no update
        initComponents();
        id = imv.getId();
        jTextFielRua.setText(imv.getRua());
        jTextFieldNumero.setText(Integer.toString(imv.getNumero()));//convertendo para String
        jTextFielBairro.setText(imv.getBairro());
        jTextFielCidade.setText(imv.getCidade());
        jTextFielEstado.setSelectedItem(imv.getEstado());
        jTextFielCep.setText(imv.getCEP());
        jTextFielTipo.setSelectedItem(imv.getTipo());
        jTextFielQtdQuartos.setText(Integer.toString(imv.getQtdQuarto()));
        jTextFielTamanho.setText(Double.toString(imv.getTamanho()));
        jTextFielValor.setText(Double.toString(imv.getValor()));
        jTextFielObs.setText(imv.getObs());
        
        vrUpDel = false;
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanelEndereco = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFielCep = new javax.swing.JFormattedTextField();
        jTextFielRua = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JFormattedTextField();
        jTextFielBairro = new javax.swing.JTextField();
        jTextFielCidade = new javax.swing.JTextField();
        jTextFielEstado = new javax.swing.JComboBox<>();
        jPanelCaracImovel = new javax.swing.JPanel();
        jButtonSalvarImovel = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextFielObs = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JToggleButton();
        jTextFielTipo = new javax.swing.JComboBox<>();
        jTextFielTamanho = new javax.swing.JFormattedTextField();
        jTextFielQtdQuartos = new javax.swing.JFormattedTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextFielValor = new javax.swing.JFormattedTextField();
        Sinalizador5 = new javax.swing.JLabel();
        Sinalizador3 = new javax.swing.JLabel();
        Sinalizador1 = new javax.swing.JLabel();
        Sinalizador = new javax.swing.JLabel();
        Sinalizador2 = new javax.swing.JLabel();
        Sinalizador4 = new javax.swing.JLabel();
        Sinalizador6 = new javax.swing.JLabel();
        Sinalizador7 = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel22.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel22.setText("Endereço:");

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel12.setText("Rua:");

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel14.setText("Numero:");

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel11.setText("CEP:");

        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel23.setText("Bairro:");

        jLabel24.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel24.setText("Cidade:");

        jLabel25.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel25.setText("Estado:");

        try {
            jTextFielCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jTextFielEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AP", "SC", "SP", "PR", "RS" }));

        jButtonSalvarImovel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonSalvarImovel.setText("Salvar");
        jButtonSalvarImovel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarImovelActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel19.setText("m²");

        jLabel20.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel20.setText("Qtd Quartos:");

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel21.setText("Tamanho:");

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel17.setText("Tipo:");

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel18.setText("Informações do Imóvel:");

        jLabel26.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel26.setText("Valor do Aluguel:");

        jLabel27.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel27.setText("Observação:");

        jTextFielObs.setForeground(new java.awt.Color(0, 0, 51));
        jTextFielObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielObsActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFielTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apartamento", "Casa", "Sobrado", "Triplex", "Cobertura", "Outro" }));

        jTextFielTamanho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jTextFielQtdQuartos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel30.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel30.setText("R$");

        jTextFielValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        Sinalizador5.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador5.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador5.setText("*");

        Sinalizador3.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador3.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador3.setText("*");

        Sinalizador1.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador1.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador1.setText("*");

        javax.swing.GroupLayout jPanelCaracImovelLayout = new javax.swing.GroupLayout(jPanelCaracImovel);
        jPanelCaracImovel.setLayout(jPanelCaracImovelLayout);
        jPanelCaracImovelLayout.setHorizontalGroup(
            jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFielObs, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                        .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel27)
                            .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sinalizador3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sinalizador1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielQtdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Sinalizador5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFielValor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCaracImovelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvarImovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar)
                .addGap(15, 15, 15))
        );
        jPanelCaracImovelLayout.setVerticalGroup(
            jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaracImovelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jTextFielTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFielQtdQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel30)
                    .addComponent(jTextFielValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sinalizador5)
                    .addComponent(Sinalizador3)
                    .addComponent(Sinalizador1))
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFielObs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCaracImovelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvarImovel)
                    .addComponent(jButtonCancelar))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        Sinalizador.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador.setText("*");

        Sinalizador2.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador2.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador2.setText("*");

        Sinalizador4.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador4.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador4.setText("*");

        Sinalizador6.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador6.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador6.setText("*");

        Sinalizador7.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        Sinalizador7.setForeground(new java.awt.Color(255, 0, 0));
        Sinalizador7.setText("*");

        javax.swing.GroupLayout jPanelEnderecoLayout = new javax.swing.GroupLayout(jPanelEndereco);
        jPanelEndereco.setLayout(jPanelEnderecoLayout);
        jPanelEnderecoLayout.setHorizontalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sinalizador4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFielBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sinalizador6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFielCidade))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sinalizador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFielRua, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Sinalizador7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFielEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sinalizador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFielCep, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCaracImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelEnderecoLayout.setVerticalGroup(
            jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFielCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sinalizador2))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFielRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sinalizador)
                    .addComponent(Sinalizador7))
                .addGap(18, 18, 18)
                .addGroup(jPanelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextFielBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jTextFielCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFielEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sinalizador4)
                    .addComponent(Sinalizador6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanelCaracImovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanelEndereco, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*
    * BOTÃO SALVAR
    * Quando acionado ele captura as informações dos campos da TelaCadImovel e chama os metodos de alteração ou inserção
    * após terminado o método de inserção ou alteração ele fecha a TelaCadImovel e abre a TelaInicial
    */
    private void jButtonSalvarImovelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarImovelActionPerformed
         Validacao validacao = new Validacao();
        //Esse if verifica se todos os campos estão preenchidos
        if ( validacao.estaVazio(jTextFielCep) && validacao.estaVazio(jTextFielRua) && validacao.estaVazio(jTextFielValor)
            && validacao.estaVazio(jTextFielBairro) && validacao.estaVazio(jTextFielCidade) && validacao.estaVazio(jTextFieldNumero) 
                && validacao.estaVazio(jTextFielTamanho) && validacao.estaVazio(jTextFielQtdQuartos)){
        
            Imovel imv = new Imovel();
            ImovelControle imvDao = new ImovelControle();

            imv.setId(id);
            imv.setCEP(jTextFielCep.getText());
            imv.setRua(jTextFielRua.getText());
            imv.setBairro(jTextFielBairro.getText());
            imv.setCidade(jTextFielCidade.getText());
            imv.setEstado(jTextFielEstado.getSelectedItem().toString());
            imv.setTipo(jTextFielTipo.getSelectedItem().toString());
            imv.setObs(jTextFielObs.getText());

            //COLOCAR DENTRO DE UM TRY CATCH PARA VERIFICAR SE FOI COLOCADO NUMERO
                imv.setValor(Double.parseDouble(jTextFielValor.getText()));
                imv.setTamanho(Double.parseDouble(jTextFielTamanho.getText()));
                imv.setNumero(Integer.parseInt(jTextFieldNumero.getText()));//fazer um if verificando se é numero
                imv.setQtdQuarto(Integer.parseInt(jTextFielQtdQuartos.getText()));

            //Esse if utiliza a variável vrUpDel para verificar se é para inserir novo ou arterar o imóvel

                if(vrUpDel){
                    imvDao.novoImovel(imv);
                } else {
                    imvDao.alteraImovel(imv);
                }

            dispose();
            TelaInicial tInicial = new TelaInicial();
            tInicial.setLocationRelativeTo(null);
            tInicial.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos sinalizados devem estar preenchidos!");
       }    
    }//GEN-LAST:event_jButtonSalvarImovelActionPerformed

    private void jTextFielObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielObsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielObsActionPerformed
   
    /*
    * BOTÃO CANCELAR
    * Botão cancelar fecha a TelaCadImovel e abre a TelaInicial
    */
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();
        TelaInicial tInicial = new TelaInicial();
        tInicial.setLocationRelativeTo(null);
        tInicial.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Sinalizador;
    private javax.swing.JLabel Sinalizador1;
    private javax.swing.JLabel Sinalizador2;
    private javax.swing.JLabel Sinalizador3;
    private javax.swing.JLabel Sinalizador4;
    private javax.swing.JLabel Sinalizador5;
    private javax.swing.JLabel Sinalizador6;
    private javax.swing.JLabel Sinalizador7;
    private javax.swing.JToggleButton jButtonCancelar;
    private javax.swing.JToggleButton jButtonSalvarImovel;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanelCaracImovel;
    private javax.swing.JPanel jPanelEndereco;
    private javax.swing.JTextField jTextFielBairro;
    private javax.swing.JFormattedTextField jTextFielCep;
    private javax.swing.JTextField jTextFielCidade;
    private javax.swing.JComboBox<String> jTextFielEstado;
    private javax.swing.JTextField jTextFielObs;
    private javax.swing.JFormattedTextField jTextFielQtdQuartos;
    private javax.swing.JTextField jTextFielRua;
    private javax.swing.JFormattedTextField jTextFielTamanho;
    private javax.swing.JComboBox<String> jTextFielTipo;
    private javax.swing.JFormattedTextField jTextFielValor;
    private javax.swing.JFormattedTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
